
name: Build, publish and deploy project to UmbHost

on:
  push:
    branches: [ main ]
env:
    SolutionName: DebayTechnics
    BuildPlatform: Any CPU
    BuildConfiguration: Release

jobs:
  build:

    runs-on: windows-latest
    
    steps:
        - name: Checkout
          uses: actions/checkout@v4
          
        - name: Setup .NET 8.x
          uses: actions/setup-dotnet@v3
          with:
            dotnet-version: '8.x'

        - name: Install dependencies
          run: dotnet restore
              
        - name: Create Build Directory
          run: mkdir _build

        - name: List files in the directory
          run: dir

        - name: Build Solution
          run: |
            dotnet build "${{env.SolutionName}}" /nologo /nr:false /p:DeployOnBuild=true /p:DeployDefaultTarget=WebPublish /p:WebPublishMethod=Package /p:PackageAsSingleFile=true /p:DeleteExistingFiles=True /p:SkipInvalidConfigurations=true /p:IncludeSetAclProviderOnDestination=False /p:AutoParameterizationWebConfigConnectionStrings=False /p:platform="${{env.BuildPlatform}}" /p:configuration="${{env.BuildConfiguration}}" /p:PackageLocation="../_build"

        - name: Deploy to UmbHost
          uses: UmbHost/umbhost-web-deploy@v1.0.3
          with:
            website-name: ${{ secrets.WEBSITE_NAME }}
            server-computer-name: ${{ secrets.SERVER_COMPUTER_NAME }}
            server-username: ${{ secrets.USERNAME }}
            server-password: ${{ secrets.PASSWORD }}
            source-path: '_build'
            source-fileName: DebayTechnics.zip
