name: Deploy to UmbHost

on:
  workflow_dispatch:
    inputs:
      deploy:
        description: 'Deploy to UmbHost'
        required: true
        type: boolean
        default: false
env:
    SolutionName: ${{ secrets.SOLUTION_NAME }}
    BuildPlatform: Any CPU
    BuildConfiguration: Release

jobs:
  approval:
    runs-on: ubuntu-latest
    steps:
    - name: Approval needed
      if: github.event.inputs.deploy == 'false'
      run: echo "Approval needed. Please approve the workflow from the Actions tab."
      continue-on-error: true
    
  build:

    runs-on: windows-latest
    
    steps:
        - name: Checkout
          uses: actions/checkout@v3.0.0

        - name: Create Build Directory
          run: mkdir -p _build

        - name: Build Solution
          run: | 
            dotnet build /nologo /nr:false /p:DeployOnBuild=true /p:DeployDefaultTarget=WebPublish /p:WebPublishMethod=Package /p:PackageAsSingleFile=true /p:DeleteExistingFiles=True /p:SkipInvalidConfigurations=true /p:IncludeSetAclProviderOnDestination=False /p:AutoParameterizationWebConfigConnectionStrings=False /p:platform="${{env.BuildPlatform}}" /p:configuration="${{env.BuildConfiguration}}" /p:PackageLocation="${{ github.workspace }}/_build"

        - name: Upload Build Artifacts
          uses: actions/upload-artifact@v3
          with:
            name: build-artifact
            path: _build

        - name: Download Build Artifacts
          uses: actions/download-artifact@v3
          with:
            name: build-artifact
            path: _build
    
        - name: List files in build directory
          run: dir _build

        - name: Deploy to UmbHost
          uses: UmbHost/umbhost-web-deploy@v1.0.1
          with:
            website-name: ${{ secrets.WEBSITE_NAME }}
            server-computer-name: ${{ secrets.SERVER_COMPUTER_NAME }}
            server-username: ${{ secrets.USERNAME }}
            server-password: ${{ secrets.PASSWORD }}
            source-path: '_build'
            source-fileName: DebayTechnics.zip
